FROM docker-registry.tools.wmflabs.org/toollabs-jessie

RUN apt-get install --yes \
    php5-cli \
    php5-curl \
    php5-gd \
    php5-imagick \
    php5-intl \
    php5-mcrypt \
    php5-mysqlnd \
    php5-pgsql \
    php5-redis \
    php5-sqlite \
    php5-xdebug \
    php5-xsl
