# Toollabs PHP runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-php
FROM {registry}/{image_prefix}-base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    php5-apcu \
    php5-cli \
    php5-curl \
    php5-gd \
    php5-imagick \
    php5-intl \
    php5-mcrypt \
    php5-mysqlnd \
    php5-pgsql \
    php5-redis \
    php5-sqlite \
    php5-xsl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
