{%- import 'macros.jinja2' as macros -%}
# Toolforge Mono runtime image
# Name: docker-registry.svc.toolforge.org/toolforge-mono612-sssd-base
FROM {{registry}}/{{image_prefix}}-trixie-sssd:{{tag}}

{{ macros.apt_install(
    [
        "mono-complete",
    ]
) }}

{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
