# Toolforge Java webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-jdk8-sssd-web
FROM {{registry}}/{{image_prefix}}-jdk8-sssd-base:{{tag}}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    toollabs-webservice \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
