#!/usr/bin/env bash
#
# Usage: ./run-image python-web
#
# Very handy when used with vagrant for local testing:
#   vagrant ssh -t -c 'toollabs-images/run-image python-web'
#
exec docker run \
    --rm --tty \
    --interactive --entrypoint /bin/bash \
    ${4:-docker-registry.tools.wmflabs.org}/${3:-toollabs}-${1:?type required}:${2:-latest}
