#!/usr/bin/env bash
#
# Usage: ./run-image python37-web
#
# Very handy when used with vagrant for local testing:
#   vagrant ssh -t -c 'toollabs-images/run-image python37-web'
#
exec docker run \
    --rm --tty \
    --interactive --entrypoint /bin/bash \
    ${4:-docker-registry.svc.toolforge.org}/${3:-toolforge}-${1:?type required}:${2:-testing}
