#!/usr/bin/python3
import os
import subprocess


def run(args):
    print('$ ' + ' '.join(args))
    subprocess.check_call(args)


venv = os.path.expanduser('~/www/python/venv')
if not os.path.isdir(venv):
    run(['python3', '-m', 'venv', venv])

pip = os.path.join(venv, 'bin/pip')
run([pip, 'install', '--upgrade', 'pip'])
requirements = os.path.expanduser('~/www/python/src/requirements.txt')
if os.path.isfile(requirements):
    run([pip, 'install', '-r', requirements])
