{%- import 'macros.jinja2' as macros -%}
# Toolforge Ruby webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-ruby21-sssd-web
FROM {{registry}}/{{image_prefix}}-ruby21-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "toollabs-webservice",
        "unicorn",
    ],
    apt_options="--force-yes"
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
