# Toollabs Python2 runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-python
FROM {registry}/{image_prefix}-base

RUN apt-get install --yes \
    python \
    python-dev \
    build-essential \
    python-virtualenv

# -dev packages needed for installing popular python packages,
# until they ship with manylinux wheels. Needs a ticket filed
# under https://phabricator.wikimedia.org/T140110
# libxml2 pip package - T140117
RUN apt-get install --yes libxml2-dev libxslt-dev zlib1g-dev
