{%- import 'macros.jinja2' as macros -%}
# Toolforge Java webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-jdk17-sssd-web
FROM {{registry}}/{{image_prefix}}-jdk17-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "toolforge-webservice",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
