# Toollabs Python 3.5 webserver image
# Name: docker-registry.tools.wmflabs.org/toollabs-python35-web
FROM {registry}/{image_prefix}-python35-base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    toollabs-webservice \
    uwsgi \
    uwsgi-plugin-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY webservice-python-bootstrap /usr/local/bin/
