{%- import 'macros.jinja2' as macros -%}
# Toolforge Golang webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-golang111-sssd-web
FROM {{registry}}/{{image_prefix}}-golang111-sssd-base:{{tag}}

# Install Python3 for backwards-compatibility. Do not
# copy forward to new images
{{ macros.apt_install(
    [
        "python3",
    ]
) }}
COPY {{image_path}}/webservice-runner /usr/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
