# Toollabs Ruby runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-ruby
FROM {registry}/{image_prefix}-base:{tag}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    build-essential \
    ruby \
    ruby-dev \
    libmysqlclient-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
