{%- import 'macros.jinja2' as macros -%}
# Toolforge mariadb/mysql maintenance image
# Name: docker-registry.tools.wmflabs.org/toolforge-mariadb-sssd-base
FROM {{registry}}/{{image_prefix}}-bullseye-sssd:{{tag}}

{{ macros.apt_install(
    [
        "logrotate",
        "mariadb-client",
        "misctools",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
