# Toolforge Python 3.7 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-web
FROM {registry}/{image_prefix}-python37-sssd-base:{tag}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    toollabs-webservice \
    uwsgi \
    uwsgi-plugin-python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY webservice-python-bootstrap /usr/local/bin/
