{%- import 'macros.jinja2' as macros -%}
# Toolforge Python 3.7 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-web
FROM {{registry}}/{{image_prefix}}-python37-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "uwsgi",
        "uwsgi-plugin-python3",
    ]
) }}

COPY webservice-python-bootstrap /usr/local/bin/
COPY webservice-runner /usr/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
