{%- import 'macros.jinja2' as macros -%}
# Toolforge Golang runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-golang111-sssd-base
FROM {{registry}}/{{image_prefix}}-buster-sssd:{{tag}}

{{ macros.apt_install(
    [
        "golang-go",
    ],
    apt_options="-t buster-backports"
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
