# Toolforge Golang runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-golang111-sssd-base
FROM {{registry}}/{{image_prefix}}-buster-sssd:{{tag}}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes -t buster-backports \
    golang-go \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
