{%- import 'macros.jinja2' as macros -%}
# Toolforge Python2 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-python2-sssd-web
FROM {{registry}}/{{image_prefix}}-python2-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "toollabs-webservice",
        "uwsgi",
        "uwsgi-plugin-python",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
