{%- import 'macros.jinja2' as macros -%}
# Toolforge Ruby runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-ruby25-sssd-base
FROM {{registry}}/{{image_prefix}}-buster-sssd:{{tag}}

{{ macros.apt_install(
    [
        "build-essential",
        "libmariadb-dev",
        "ruby",
        "ruby-dev",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
