{%- import 'macros.jinja2' as macros -%}
# Toolforge NodeJS 10 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-node10-sssd-web
FROM {{registry}}/{{image_prefix}}-node10-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "toolforge-webservice",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
