# Toollabs Python3 runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-python
FROM {registry}/{image_prefix}-base

RUN apt-get install --yes \
    python3 \
    python3-dev \
    build-essential \
    python3-virtualenv
