{%- import 'macros.jinja2' as macros -%}
# Toolforge Ruby webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-ruby25-sssd-web
FROM {{registry}}/{{image_prefix}}-ruby25-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "toollabs-webservice",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
