# Toolforge Ruby webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-ruby25-sssd-web
FROM {registry}/{image_prefix}-ruby25-sssd-base:{tag}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    toollabs-webservice \
    unicorn \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
