{%- import 'macros.jinja2' as macros -%}
# Toolforge tcl runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-tcl86-sssd-base
FROM {{registry}}/{{image_prefix}}-stretch-sssd:{{tag}}

# Bugs T58995
{{ macros.apt_install(
    [
        "mysqltcl",
        "tcl",
        "tcl-thread",
        "tcl-tls",
        "tcl-trf",
        "tclcurl",
        "tcllib",
        "tdom",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
