{%- import 'macros.jinja2' as macros -%}
# Toolforge tcl runtime image
# Name: docker-registry.svc.toolforge.org/toolforge-tcl86-sssd-base
FROM {{registry}}/{{image_prefix}}-trixie-sssd:{{tag}}

# Bugs T58995
{{ macros.apt_install(
    [
        "mysqltcl",
        "tcl",
        "tcl-thread",
        "tcl-tls",
        "tcl-trf",
        "tclcurl",
        "tcllib",
        "tdom",
    ]
) }}
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
