# Toollabs Python2 webserver image
# Name: docker-registry.tools.wmflabs.org/toollabs-python-web
FROM {registry}/{image_prefix}-python2-base

RUN apt-get install --yes \
    uwsgi \
    uwsgi-plugin-python

RUN apt-get install --yes toollabs-webservice
