{%- import 'macros.jinja2' as macros -%}
# Run image for the Toolforge bullseye0 buildpacks
# Name: docker-registry.svc.toolforge.org/toolforge-bullseye0-run
# Sets up:
#   Whatever is needed at runtime by everything
FROM {{registry}}/{{image_prefix}}-bullseye0-base:{{tag}}

USER tfb

{# vim: set sw=4 ts=4 sts=4 et ft=django: #}

