{%- import 'macros.jinja2' as macros -%}
# Toolforge PHP 8.4 webserver image
# Name: docker-registry.svc.toolforge.org/toolforge-php84-sssd-web
FROM {{registry}}/{{image_prefix}}-php84-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "lighttpd",
        "php8.4-cgi",
    ]
) }}

COPY shared/lighttpd/webservice-runner /usr/bin/
RUN touch /etc/toolforge-enable-php
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
