# Toollabs NodeJS webserver image
# Name: docker-registry.tools.wmflabs.org/toollabs-nodejs-web
FROM {registry}/{image_prefix}-nodejs-base:{tag}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    toollabs-webservice \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
