{%- import 'macros.jinja2' as macros -%}
# Toolforge NodeJS 16 webserver image
# Name: docker-registry.svc.toolforge.org/toolforge-node16-sssd-web
FROM {{registry}}/{{image_prefix}}-node16-sssd-base:{{tag}}

# Install Python3 for backwards-compatibility. Do not
# copy forward to new images
{{ macros.apt_install(
    [
        "python3",
    ]
) }}
COPY shared/node/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
