{%- import 'macros.jinja2' as macros -%}
# Toolforge tcl webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-tcl86-sssd-web
FROM {{registry}}/{{image_prefix}}-tcl86-sssd-base:{{tag}}

# python3 is backwards compat from the old webservice-runner, do not copy forward!
{{ macros.apt_install(
    [
        "libfcgi-dev",
        "lighttpd",
        "python3",
    ]
) }}

COPY shared/lighttpd/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
