{%- import 'macros.jinja2' as macros -%}
# Toolforge tcl webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-tcl86-sssd-web
FROM {{registry}}/{{image_prefix}}-tcl86-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "libfcgi-dev",
        "lighttpd",
    ]
) }}

COPY shared/lighttpd/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
