{%- import 'macros.jinja2' as macros -%}
# Toolforge NodeJS 18 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-node18-sssd-web
FROM {{registry}}/{{image_prefix}}-node18-sssd-base:{{tag}}

COPY shared/node/webservice-runner /usr/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
