# Toollabs Python3 webserver image
# Name: docker-registry.tools.wmflabs.org/toollabs-python-web
FROM {registry}/{image_prefix}-python-base

RUN apt-get install --yes \
    uwsgi \
    uwsgi-plugin-python3

RUN apt-get install --yes toollabs-webservice
