{%- import 'macros.jinja2' as macros -%}
# Toolforge Java 21 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-jdk21-sssd-web
FROM {{registry}}/{{image_prefix}}-jdk21-sssd-base:{{tag}}

COPY shared/generic/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
