{%- import 'macros.jinja2' as macros -%}
# Toolforge Ruby runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-ruby21-sssd-base
FROM {{registry}}/{{image_prefix}}-jessie-sssd:{{tag}}

{{ macros.apt_install(
    [
        "build-essential",
        "libmysqlclient-dev",
        "ruby",
        "ruby-dev",
    ],
    apt_options="--force-yes"
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
