{%- import 'macros.jinja2' as macros -%}
# Toolforge Mono runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-mono68-sssd-base
FROM {{registry}}/{{image_prefix}}-bullseye-sssd:{{tag}}

{{ macros.apt_install(
    [
        "mono-complete",
    ]
) }}

# Hack around https://github.com/mono/mono/issues/21233
RUN sed -i 's#mozilla/DST_Root_CA_X3.crt#!mozilla/DST_Root_CA_X3.crt#' /etc/ca-certificates.conf && update-ca-certificates
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
