{%- import 'macros.jinja2' as macros -%}
# Toolforge Mono runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-mono68-sssd-base
FROM {{registry}}/{{image_prefix}}-bullseye-sssd:{{tag}}

{{ macros.apt_install(
    [
        "mono-complete",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
