{%- import 'macros.jinja2' as macros -%}
# Toolforge PHP 8.2 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-php82-sssd-web
FROM {{registry}}/{{image_prefix}}-php82-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "lighttpd",
        "php8.2-cgi",
    ]
) }}

COPY shared/lighttpd/webservice-runner /usr/bin/
RUN touch /etc/toolforge-enable-php
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
