{%- import 'macros.jinja2' as macros -%}
# Toolforge Java runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-jdk11-sssd-base
FROM {{registry}}/{{image_prefix}}-buster-sssd:{{tag}}

RUN mkdir -p /usr/share/man/man1
{{ macros.apt_install(
    [
        "openjdk-11-jdk",
        "maven",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
