{%- import 'macros.jinja2' as macros -%}
# Toolforge Debian 13 webserver image
# Name: docker-registry.svc.toolforge.org/toolforge-trixie-sssd-web
FROM {{registry}}/{{image_prefix}}-trixie-sssd:{{tag}}

COPY shared/generic/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
