{%- import 'macros.jinja2' as macros -%}
# Toolforge Python3 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-python34-sssd-web
FROM {{registry}}/{{image_prefix}}-python34-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "toollabs-webservice",
        "uwsgi",
        "uwsgi-plugin-python3",
    ],
    apt_options="--force-yes"
) }}

COPY webservice-python-bootstrap /usr/local/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
