# Toollabs Ruby webserver image
# Name: docker-registry.tools.wmflabs.org/toollabs-ruby-web
FROM {registry}/{image_prefix}-ruby-base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    toollabs-webservice \
    unicorn \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
