{%- import 'macros.jinja2' as macros -%}
# Toolforge Java runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-jdk8-sssd-base
FROM {{registry}}/{{image_prefix}}-stretch-sssd:{{tag}}

{{ macros.apt_install(
    [
        "maven",
        "openjdk-8-jdk",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
