# Toolforge Java runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-jdk8-sssd-base
FROM {{registry}}/{{image_prefix}}-stretch-sssd:{{tag}}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    openjdk-8-jdk \
    maven \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
