{%- import 'macros.jinja2' as macros -%}
# Toolforge Debian 12 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-bookworm-sssd-web
FROM {{registry}}/{{image_prefix}}-bookworm-sssd:{{tag}}

COPY shared/generic/webservice-runner /usr/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
