# Toollabs lighttpd based Static File Server
# Name: docker-registry.tools.wmflabs.org/toollabs-static-web
FROM {registry}/{image_prefix}-base

RUN apt-get install --yes lighttpd

RUN apt-get install --yes toollabs-webservice

# This is where lighttpd puts its config files.
# Very unideal, but let's stick to same places as
# the gridengine for right now
RUN chmod 0777 /var/run/lighttpd/
