{%- import 'macros.jinja2' as macros -%}
# Toolforge PHP 7.4 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-php74-sssd-web
FROM {{registry}}/{{image_prefix}}-php74-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "lighttpd",
        "lighttpd-mod-openssl",
        "php7.4-cgi",
    ]
) }}

COPY shared/lighttpd/webservice-runner /usr/bin/
RUN touch /etc/toolforge-enable-php
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
