{%- import 'macros.jinja2' as macros -%}
# Toolforge Ruby 3.1 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-ruby31-sssd-web
FROM {{registry}}/{{image_prefix}}-ruby31-sssd-base:{{tag}}

COPY webservice-runner /usr/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
