{%- import 'macros.jinja2' as macros -%}
# Toolforge Perl 5.40 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-perl540-sssd-web
FROM {{registry}}/{{image_prefix}}-perl540-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "lighttpd",
    ]
) }}

COPY shared/lighttpd/webservice-runner /usr/bin/
RUN touch /etc/toolforge-enable-perl
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
