# Toollabs Java runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-jdk8
FROM {registry}/{image_prefix}-stretch:{tag}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    openjdk-8-jdk \
    maven \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
