# Toollabs Java runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-jdk8
FROM {registry}/{image_prefix}-base

RUN apt-get install --yes -t jessie-backports \
    openjdk-8-jdk \
    maven
