{%- import 'macros.jinja2' as macros -%}
# Toolforge Python 3.11 webserver image
# Name: docker-registry.svc.toolforge.org/toolforge-python311-sssd-web
FROM {{registry}}/{{image_prefix}}-python311-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "uwsgi",
        "uwsgi-plugin-python3",
    ]
) }}

COPY shared/python/webservice-python-bootstrap /usr/local/bin/
COPY shared/python/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
