{%- import 'macros.jinja2' as macros -%}
# Toolforge Perl 5.36 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-perl536-sssd-web
FROM {{registry}}/{{image_prefix}}-perl536-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "lighttpd",
    ]
) }}

COPY shared/lighttpd/webservice-runner /usr/bin/
RUN touch /etc/toolforge-enable-perl
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
