{%- import 'macros.jinja2' as macros -%}
# Toolforge NodeJS 20 webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-node20-sssd-web
FROM {{registry}}/{{image_prefix}}-node20-sssd-base:{{tag}}

COPY shared/node/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
