{%- import 'macros.jinja2' as macros -%}
# Toolforge Java runtime image
# Name: docker-registry.svc.toolforge.org/toolforge-jdk17-sssd-base
FROM {{registry}}/{{image_prefix}}-bullseye-sssd:{{tag}}

RUN mkdir -p /usr/share/man/man1  # The day it works without this, remove this.

{{ macros.apt_install(
    [
        "openjdk-17-jdk",
        "maven",
    ]
) }}

{# vim: set sw=4 ts=4 sts=4 et ft=django: #}

