{%- import 'macros.jinja2' as macros -%}
# Toolforge NodeJS webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-node6-sssd-web
FROM {{registry}}/{{image_prefix}}-node6-sssd-base:{{tag}}

# Install Python3 for backwards-compatibility. Do not
# copy forward to new images
{{ macros.apt_install(
    [
        "python3",
    ]
) }}
COPY webservice-runner /usr/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
