{%- import 'macros.jinja2' as macros -%}
# Toolforge NodeJS webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-node6-sssd-web
FROM {{registry}}/{{image_prefix}}-node6-sssd-base:{{tag}}

{{ macros.apt_install(
    [
        "toollabs-webservice",
    ]
) }}
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
