# Toollabs NodeJS runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-nodejs
FROM {registry}/{image_prefix}-base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    nodejs-legacy \
    npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
