# Toolforge Java runtime image
# Name: docker-registry.tools.wmflabs.org/toolforge-jdk11-base
FROM {registry}/{image_prefix}-buster:{tag}

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    openjdk-11-jdk \
    maven \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
