{%- import 'macros.jinja2' as macros -%}
# Toolforge Ruby 3.3 webserver image
# Name: docker-registry.svc.toolforge.org/toolforge-ruby33-sssd-web
FROM {{registry}}/{{image_prefix}}-ruby33-sssd-base:{{tag}}

COPY shared/generic/webservice-runner /usr/bin/
{# vim: set sw=4 ts=4 sts=4 et ft=django: #}
