{%- import 'macros.jinja2' as macros -%}
# Toolforge Ruby webserver image
# Name: docker-registry.tools.wmflabs.org/toolforge-ruby27-sssd-web
FROM {{registry}}/{{image_prefix}}-ruby27-sssd-base:{{tag}}

# Install Python3 for backwards-compatibility. Do not
# copy forward to new images
{{ macros.apt_install(
    [
        "python3",
    ]
) }}
COPY shared/generic/webservice-runner /usr/bin/
{# vim:sw=4:ts=4:sts=4:et:ft=django: #}
