# Toollabs Java webserver image
# Name: docker-registry.tools.wmflabs.org/toollabs-java-web
FROM {registry}/{image_prefix}-jdk8-base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes \
    toollabs-webservice \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
