# Toollabs Golang runtime image
# Name: docker-registry.tools.wmflabs.org/toollabs-golang
FROM {registry}/{image_prefix}-base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes -t jessie-backports \
    golang-go \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
